
name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Enviroinment Check 
      run: env

      - name: Installing make & other tools
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: Fetching source code
        uses: actions/checkout@v4
      
      - name: Setup GoogleTest
        uses: Bacondish2023/setup-googletest@v1
        with:
          tag: v1.14.0  # specify the version you want to use

      - name: Build main app
        run: |
          source ./build.sh
      
      - name: Build and run gtests
        run: |
          ./build.sh test
          ./tests

    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip

    - name: Run Python tests
      run: |
        python3 test/test_random.py
